# NAME : Fan Shi
# EMAIL : fanshi2@g.ucla.edu
# ID : 805256911

default:
			gcc -Wall -Wextra lab1a.c -o lab1a

dist:
			tar -czf lab1a-805256911.tar.gz lab1a.c Makefile README

clean:
			rm -f lab1a lab1a-805256911.tar.gz
